version: "3"
services:
  database:
    image: mongo
    container_name: gonode_mongo
    volumes:
      - db-data:/var/lib/mongo/data
    ports:
      - 27017:27017
    restart: always
volumes:
  db-data:
    driver: local
